@@grammar::Ostw
@@eol_comments :: /\/\/.*?$/
@@keyword :: If Else While For Rule variables actions conditions event global player End
@@keyword :: conditions event global player End settings modes heroes struct class enum



start = {root_elements}+ $ ;
root_elements
    =
    | enum
    | ';'.{import}*
    | assignment
    | token
    | class_decl
    | rule
#    | subroutine
#    | macro
#    | if
#    | switch
    ;

literal_values
    =
    | number
    | bool
    | string
    | array
    | tuple
    ;
LITERAL_VALUES = >literal_values;



array = '[' @:','.{expr} ']';
tuple = '(' @:','.{expr} ')';

func_call = &(ident '(') func_name:ident '(' ~ ','.{{args:expr}* {kwargs:kwarg}*}* ')' ;
index_access = &(ident '[') index_name:ident '[' ~ [index:expr] ']' ;

kwarg = ident ':' expr ;
token
    =
    | literal_values
    | token_complex
    | token_simple
    ;

token_base
    =
    | >index_access
    | >func_call
    | ident
    ;
token_child
    =
    | >index_access
    | >func_call
    | ident
    ;

token_simple = token_base ;
token_complex = token_base [r'.' r'.'.{token_child}+ ];


# tokens grouped together
expr = (math_symbols).{token}+ ;


lambda_params
    =
    | '(' @:','.{expr}+ ')'
    | expr
    ;
lambda = lambda_params '=' '>' expr ;

delete = 'delete' token ;
statements
    =
    | delete
    | `TODO`
    ;
one_expr = expr $ ;

#include :: "import.ebnf"
#include :: "enum.ebnf"
#include :: "class.ebnf"
#include :: "rule.ebnf"
#include :: "variable.ebnf"
#include :: "base.ebnf"
#include :: "math.ebnf"
##include :: "struct.ebnf"