@@grammar::Ostw
@@eol_comments :: /\/\/.*?$/
@@keyword :: If Else While For Rule variables actions conditions event global player End
@@keyword :: conditions event global player End settings modes heroes struct class enum



start = {root_elements}+ $ ;
root_elements
    =
    | enum
    | ';'.{import}*
    | assignment
    | token
    | class_decl
    | rule
#    | subroutine
#    | macro
#    | if
#    | switch
    ;

literal_values
    =
    | number
    | bool
    | string
    | array
    | tuple
    ;
LITERAL_VALUES = >literal_values;



array = '[' @:','.{expr} ']';
tuple = '(' @:','.{expr} ')' !arrow;

func_predicate = '(' ~ ','.{{args:expr !':'}* {kwargs:kwarg}*}* ')' ;
func_call = &(ident '(') func_name:ident func_predicate ;
index_predicate = '[' ~ [index:expr] ']' ;
index_access = &(ident '[') ident index_predicate ;

kwarg = key:ident ':' value:expr ;
token
    =
    | lambda
    | literal_values
    | token_complex
    | token_simple
    ;

token_simple = ident [index_predicate|func_predicate];
token_complex = '.'.{token_simple};
token_math = token math_symbol token;


# tokens grouped together
expr = (math_symbols)<{token_math|token}+ ;


lambda_params
    =
    | '(' @:','.{expr}+ ')'
    | expr
    ;
lambda = lambda_params '=' '>' expr ;

delete = 'delete' token ;
statements
    =
    | delete
    | `TODO`
    ;
one_expr = expr $ ;

#include :: "import.ebnf"
#include :: "enum.ebnf"
#include :: "class.ebnf"
#include :: "rule.ebnf"
#include :: "variable.ebnf"
#include :: "base.ebnf"
#include :: "math.ebnf"
##include :: "struct.ebnf"