# Numeric literals
ONE_NUMBER = /\d/ ;
NUMERIC = /\d+/ ;
DOT = '.' ;
neg = '-';
E = 'e';
OP
    =
    | '+'
    | '-'
    ;
SCI_NOTE = E OP NUMERIC ;

number = [neg] NUMERIC [DOT NUMERIC [SCI_NOTE]] ;

math_symbol
    =
    | '+'
    | '-'
    | '*'
    | '/'
    ;


actual_math = literal_values math_symbol literal_values ;