# most tokens
IDENT =  /[a-zA-Z0-9_]+/ ;
# For when we do want to skip whitespace
ident = IDENT;

# Strings
DBL_QUOTE = '"' ;
SNGL_QUOTE = "'" ;
ANYTHING_BUT_DBL_QUOTE = /[^"\n]+/ ;
ANYTHING_BUT_SNGL_QUOTE = /[^'\n]+/ ;
dbl_quote_string = DBL_QUOTE ANYTHING_BUT_DBL_QUOTE DBL_QUOTE;
sngl_quote_string = SNGL_QUOTE ANYTHING_BUT_SNGL_QUOTE SNGL_QUOTE;
string
    =
    | sngl_quote_string
    | dbl_quote_string
    ;

# Boolean
bool
    =
    | 'true'
    | 'false'
    ;