class_start = 'class ' name: IDENT;
class_body = '{' {class_body_parts}* '}';
class_body_parts
    =
    | class_variable
    | class_method
    ;
class_instantiation = 'TODO';
class_variable = 'TODO';
class_method = 'TODO';
class = class_start class_body ;