# Numeric literals
ONE_NUMBER = /\d/ ;
NUMERIC = /\d+/ ;
DOT = '.' ;
FLOAT = [NEG] NUMERIC DOT NUMERIC SCI_NOTE;
NEG = '-';
INT = [NEG] NUMERIC;
E = 'e';
OP
    =
    | '+'
    | '-'
    ;
SCI_NOTE
    =
    | &E OP NUMERIC
    | () `False`
    ;

NUMBER_TYPES
    =
    | FLOAT
    | INT
    ;

number = NUMBER_TYPES;
NUMBER = number ;


math_symbol
    =
    | '+'
    | '-'
    | '*'
    | '/'
    ;


math = literal_values math_symbol literal_values ;