
# declarations
scope
    =
    | 'globalvar' scope: `GLOBAL`
    | 'playervar' scope: `PLAYER`
    | scope: `None`
    ;

ARRAY
    =
    |'[]' is_array: `True`
    | is_array: `False`
    ;
EXTENDED
    =
    | '!' is_extended: `True`
    | is_extended: `False`
    ;
variable_attributes
    =
    | 'public'
    | 'private'
    | 'protected'
    | 'virtual'
    | 'override'
    | 'abstract'
    | 'static'
    | 'globalvar'
    | 'playervar'
    ;
declaration = scope token_type token_name ['=' expr] ';';
token_name = token ARRAY EXTENDED ;
token_type
    =
    | 'define'
    | ident ARRAY
    ;


assign_symbol
    =
    | '=' action: `ASSIGN`
    | '+=' action: `ADD`
    | '-=' action: `SUBTRACT`
    | '*=' action: `MULTIPLY`
    | '/=' action: `DIVIDE`
    | '%=' action: `DIVREM` # Better name for this I think, divide and assign remainder
    | '^=' action: `POWER`
    ;
mod_symbol
    =
    | '++' action: `INCREMENT`
    | '--' action: `DECREMENT`
    ;
assignment = expr (assign_symbol expr| mod_symbol) ';' ;




